### ISSUE TITLE
ERROR ReferenceError: JsStore is not defined

### ISSUE THREAD

**Issue by AlaaJamous** [ujjwalguptaofficial/JsStore#43] opened 2018-05-06 07:24 UTC
Dear All, i tried to run my angular 5 application inside a webworker but i faced an issue where it tells me that JsStore Is not defined. 
any one faced a slimier issue?
below a screenshot for the error i'm facing.
thanks, 
![image](https://user-images.githubusercontent.com/10616844/39670919-79bb6c48-5117-11e8-81d7-2fb6cbed26b0.png)

**Comment by ujjwalguptaofficial** [comment] 2018-05-06 07:28
Hi - it seems like you have not included jsstore in index.html.

**Comment by ujjwalguptaofficial** [comment] 2018-05-06 08:46
what do you mean by wrapping the application inside a worker ?

**Comment by AlaaJamous** [comment] 2018-05-06 09:00
i used platform-worker instead of platform-browser in angular 5. 
you can refer to the below link to see the tutorial i used to convert my application.
https://blog.angularindepth.com/angular-with-web-workers-step-by-step-dc11d5872135

**Comment by ujjwalguptaofficial** [comment] 2018-05-06 09:13
By default jsstore - executes itself inside web worker, so you don't need to use the above way. You just need to include in index,html and after that it will take care of executing in web worker. 

Fyi - you can use the above way in version2 which will be uploaded by next week.

**Comment by ujjwalguptaofficial** [comment] 2018-05-12 05:44
@AlaaJamous - As we talk : - Just pasting summary of our conversation for future use.

Problem :  you were building jsstore inside a worker and getting this problem.
Solution :- You cant because jsstoer itslef uses a worker and there are some business logic which takes place from taking data from api, passing to worker and passing back the result to user. 

So the solution will be to let jsstore handles its code in its own worker and pass data from jsstore output to your worker.

Hope the problem is solved. I am closing this issue, feel free to reopen.

Thanks

**Closed by ujjwalguptaofficial** 2018-05-12 05:44 UTC
