### ISSUE TITLE
And with OR operator

### ISSUE THREAD

**Issue by anujkumar10** [ujjwalguptaofficial/JsStore#14] opened 2018-01-03 14:32 UTC
customerId:parseInt(customerIdValue),
             stockNumber: { Like: '%' + searchValue + '%' },
             Or: {
             stockDescription: { Like: '%' + searchValue + '%'} 
             }

In the above example, customerIdValue should be present in customerId column and
searchValue should be present in stockNumber or stockDescription column.

Please help how to accomplish this in jsstore.

**Comment by ujjwalguptaofficial** [comment] 2018-01-04 03:58
The query that you have written is right. Isn't it working for you?

**Comment by ujjwalguptaofficial** [comment] 2018-01-04 04:07
The query you have written is equivalent to sql - 

`select * from <table_name> where customerId=customerIdValue and stockNumber Like '%' + searchValue + '%' or stockDescription Like '%' + searchValue + '%'`

Let me know if your query is something else. You can write the equivalent sql query.

**Comment by anujkumar10** [comment] 2018-01-04 04:51
Please check the below query that i want to accomplish using jsstore library

SELECT * FROM Customers
WHERE customerId=customerIdValue AND (stockNumber =searchValue OR stockDescription=searchValue);

Thanks a lot for your help.

**Comment by ujjwalguptaofficial** [comment] 2018-01-04 04:57
The query for - 
```

SELECT * FROM Customers
WHERE customerId=customerIdValue AND (stockNumber =searchValue OR stockDescription=searchValue);
```

will be-

```
customerId: parseInt(customerIdValue),
Or: {
    stockDescription: {
        Like: '%' + searchValue + '%'
    },
    stockNumber: {
        Like: '%' + searchValue + '%'
    }
}
```

Hope this will work for you.

**Comment by anujkumar10** [comment] 2018-01-04 05:02
This does not work because it makes customerId optional, 

 customer id should match and either of stockdescription or stockNumber should match.

**Comment by ujjwalguptaofficial** [comment] 2018-01-04 05:10
yes, you are right. This is a very interesting case. Give me some time, I will let you know the exact query. It may be that I have to add some extra code.

Thanks for such an interesting case.

**Comment by anujkumar10** [comment] 2018-01-04 05:12
sure.Thanks for quick response.

Will be waiting for your reply

**Comment by anujkumar10** [comment] 2018-01-04 12:46
Hi ujjwal,
could you give me a timeframe u could solve this in, as i am struck in tight timeline.

Sorry for the impatience.

**Comment by ujjwalguptaofficial** [comment] 2018-01-04 16:06
Hey there - I can understand that. I cant promise you but I will try to do it by the end of this week ?

Can you tell me when is ur timeline ?

**Comment by anujkumar10** [comment] 2018-01-04 20:02
We have final POC presentation meeting at 9th Jan.
If we are able to present certain functionalities in offline, then we get the project.

**Comment by ujjwalguptaofficial** [comment] 2018-01-05 03:13
ok great, I will try to do it before Monday. Hope you will get your project.

**Comment by ujjwalguptaofficial** [comment] 2018-01-06 05:28
Hi @anujkumar10 - the issue is resolved. I have to add some code for this. 

The code for the sql query -
```
SELECT * FROM Customers
WHERE customerId=customerIdValue AND (stockNumber =searchValue OR stockDescription=searchValue);
```

will be - 

```
var  Con = new JsStore.Instance(<db_name>);
Con.select(
    From : Customers,
    Where:[
        {
            customerId: customerIdValue
        } ,
        {
            stockNumber: searchValue ,
            Or:{
                stockDescription: searchValue
            }
        }
        ]
)
```

Hope this will work for you. Let me know if there is something else I can help with ?

**Comment by anujkumar10** [comment] 2018-01-06 19:17
Hi Ujjawal,
 Where:[
        {
            customerId: customerIdValue
        } ,
        {
            stockNumber: searchValue ,
            Or:{
                stockDescription: searchValue
            }
        }
        ]
Above is not working as expected. It gives me results for all customers and not of particular customer which is passed(customerIdValue).



In the update library, simple AND condition has also stopped working.
eg.
Where: 
{
            customerId: customerIdValue,
            stockDescription: { Like: '%' + searchValue + '%'}
 } does not work.It was  working  with the previous version of library before you just today updated.


Whereas:

Where: 
        {
            customerId: customerIdValue
}

Where: 
        {
            stockDescription: { Like: '%' + searchValue + '%'}
        }

separately works fine.

**Comment by anujkumar10** [comment] 2018-01-06 19:40
I have donwloaded the latest version of library from:
https://cdn.jsdelivr.net/npm/jsstore

**Comment by ujjwalguptaofficial** [comment] 2018-01-07 03:11
Seems like latest version is not reflected on cdnjs. It may take time.

Try this out - https://cdn.jsdelivr.net/npm/jsstore@1.4.0

You are using 1.3.3. and the latest version is 1.4.0. Please let me know your result. 

Thanks

**Comment by ujjwalguptaofficial** [comment] 2018-01-07 03:18
I just tried this query and its working.

![image](https://user-images.githubusercontent.com/10938615/34646180-5a2523bc-f387-11e7-8be3-b7138ba0a772.png)

**Comment by ujjwalguptaofficial** [comment] 2018-01-10 03:00
Are we good here. Should I close this issue ?

**Comment by anujkumar10** [comment] 2018-01-10 11:23
Please give me a day or two, i will confirm. Thanks

**Comment by anujkumar10** [comment] 2018-01-12 12:02
I am facing another issue, if i have created database with few tables today, and I open the app next day(or after few hours) and look at the tables, sometimes few columns are missing .

Hence the queries stop working because the columns are missing.

**Comment by anujkumar10** [comment] 2018-01-12 12:34
size of the database is around 29mb as of now

**Comment by ujjwalguptaofficial** [comment] 2018-01-12 15:05
Cant tell what the issue is. It must be something with browser, or may be something wrong with the code.

I will say - please spend some time, it may take some time to figure out the right way to do it. Although I am trying to show a proper error message for every thing and making indexeddb easier.

Use try catch every where, due to too much error - Indexeddb database may become buggy and in that case browser may delete db or something unpleasant may happens. Build a solid code without any issue and then issue if this is happening anymore.

**Comment by ujjwalguptaofficial** [comment] 2018-01-12 15:06
Btw - if you find something in console, please share with us. Or if any particular case, where it is arising please share and feel free to reach.

**Comment by anujkumar10** [comment] 2018-01-12 15:10
Yes sure, if there any size limitations with indexed db ?
Till what size you have tested it?

**Comment by ujjwalguptaofficial** [comment] 2018-01-12 15:15
I have tested with text for 10 mb and using blobs for 150mb. It was good.

**Comment by ujjwalguptaofficial** [comment] 2018-01-12 15:19
> if there any size limitations with indexed db ?

yes , it depends on browsers. 

check this out - https://stackoverflow.com/questions/5692820/maximum-item-size-in-indexeddb

**Comment by ujjwalguptaofficial** [comment] 2018-01-15 02:54
closing the issue.

**Comment by anujkumar10** [comment] 2018-01-15 06:20
![image](https://user-images.githubusercontent.com/22892942/34929481-1af3b710-f992-11e7-95ef-9d1bbc34c4a3.png)

Please check this screenshot, i am entering raw value('gffdgfdg') in country(which is mandatory) but it still returns result

**Comment by ujjwalguptaofficial** [comment] 2018-01-15 15:56
nice catch. Thanks for the screenshot. I will fix it asap.

**Comment by ujjwalguptaofficial** [comment] 2018-01-16 03:34
Solved. There was a small bug. please check and let me know.

**Comment by ujjwalguptaofficial** [comment] 2018-01-24 04:56
Hope everything is running fine. Closing the issue.

**Comment by anujkumar10** [comment] 2018-01-24 07:58
Yes looks fine. Thanks for the help

**Closed** 2018-01-25 03:17 UTC
Labels: help wanted
