### ISSUE TITLE
between not inclusive

### ISSUE THREAD

**Issue by Madman600** [ujjwalguptaofficial/JsStore#202] opened 2021-04-16 17:31 UTC
The between operator is not inclusive as it should be.

**Comment by ujjwalguptaofficial** [comment] 2021-04-17 01:01
@Madman600 could you add some description ? an example perhaps.

**Comment by Madman600** [comment] 2021-04-17 01:16
If I select using between 1 and 10 , only 2-9 will be returned.  It should return 1-10.

**Comment by ujjwalguptaofficial** [comment] 2021-04-17 02:16
This is with multiple column query in where right ? If there is no issue, could you paste your query please.

**Comment by ujjwalguptaofficial** [comment] 2021-04-20 02:47
There was issue with filtering when where has multiple column. e.g -

```
select({
   from:'Products',
   where:{
      id: 5,
      price:{
        '>':10
      }
   }
})
```

This has been fixed in new version - 3.13.6

**Closed** 2021-04-20 02:47 UTC

**Comment by Madman600** [comment] 2021-04-21 16:54
Between is still an issue it's only returning < high, not <= high.

**Comment by ujjwalguptaofficial** [comment] 2021-04-22 01:38
@Madman600 not able to reproduce, if you can provide a query or a POC then i will be able to look.
